contact_links:
  - name: Discord
    url: https://discord.gg/Mb4nXQD
    about: Discord support server
  - name: Forum
    url: https://forum.kerbalspaceprogram.com/index.php?/topic/197082-*
    about: KSP forum support thread
