name: Feature request
description: Suggest an idea for CKAN
title: "[Feature]: "
labels: [Enhancement]
body: 
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: Is your feature request related to a problem? Please describe.
      placeholder: I am always frustrated when...
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: Describe the solution you would like
      placeholder: I would like that you implement this...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Describe alternatives you have considered (if applicable)

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Provide some additional context (if applicable)
