name: Mod request
description: Suggest a mod to be added to CKAN
title: "[Mod]: "
labels: [Mod-request]
body:
  - type: input
    id: mod-name
    attributes:
      label: Mod Name
      description: What is the name of the mod you want to add to CKAN?
    validations:
      required: true

  - type: input
    id: mod-author
    attributes:
      label: Author(s)
      description: Who is the creator and/or maintainer of the mod?
    validations:
      required: true

  - type: input
    id: mod-license
    attributes:
      label: License
      description: What is the license of the mod?
    validations:
      required: true

  - type: input
    id: mod-homepage
    attributes:
      label: Homepage link
      description: Where can we find more information about the mod? (forum, spacedock, github, ...)
    validations:
      required: true

  - type: input
    id: mod-download
    attributes:
      label: Download link
      description: Where can users download the mod?
    validations:
      required: true
